import { supabase } from "../lib/supabase";

export async function registerUser({ email, password, displayName, username }) {
  const { data, error } = await supabase.auth.signUp({ email, password, options: { data: { display_name: displayName, username } } });
  if (error) throw error;
  return data;
}
export async function loginUser(email, password) { const { data, error } = await supabase.auth.signInWithPassword({ email, password }); if (error) throw error; return data; }
export async function logoutUser() { const { error } = await supabase.auth.signOut(); if (error) throw error; }
export async function getCurrentProfile(userId) { const { data, error } = await supabase.from("profiles").select("*").eq("id", userId).single(); if (error) throw error; return data; }
export async function updateProfile(userId, values) { const { data, error } = await supabase.from("profiles").update(values).eq("id", userId).select().single(); if (error) throw error; return data; }
export async function getFeed() { const { data, error } = await supabase.from("posts").select("id, content, media_url, media_type, created_at, author_id, profiles!posts_author_id_fkey(id, display_name, username, avatar_url), likes(user_id), comments(count)").order("created_at", { ascending: false }).limit(50); if (error) throw error; return data || []; }
export async function createPost(authorId, content, mediaUrl = null, mediaType = null) { const { data, error } = await supabase.from("posts").insert({ author_id: authorId, content, media_url: mediaUrl, media_type: mediaType }).select().single(); if (error) throw error; return data; }
export async function toggleLike(userId, postId, liked) { if (liked) { const { error } = await supabase.from("likes").delete().match({ user_id: userId, post_id: postId }); if (error) throw error; } else { const { error } = await supabase.from("likes").insert({ user_id: userId, post_id: postId }); if (error) throw error; } }
export async function addComment(authorId, postId, content) { const { data, error } = await supabase.from("comments").insert({ author_id: authorId, post_id: postId, content }).select("*, profiles!comments_author_id_fkey(display_name, username, avatar_url)").single(); if (error) throw error; return data; }
export async function followUser(followerId, followingId, following) { if (following) { const { error } = await supabase.from("follows").delete().match({ follower_id: followerId, following_id: followingId }); if (error) throw error; } else { const { error } = await supabase.from("follows").insert({ follower_id: followerId, following_id: followingId }); if (error) throw error; } }
export async function searchProfiles(term) { const { data, error } = await supabase.from("profiles").select("id, display_name, username, avatar_url").or(`display_name.ilike.%${term}%,username.ilike.%${term}%`).limit(10); if (error) throw error; return data || []; }
export async function getNotifications(userId) { const { data, error } = await supabase.from("notifications").select("*, actor:profiles!notifications_actor_id_fkey(display_name, username, avatar_url)").eq("recipient_id", userId).order("created_at", { ascending: false }).limit(20); if (error) throw error; return data || []; }
export async function uploadImage(userId, file, bucket = "post-media") { const extension = file.name.split(".").pop(); const path = `${userId}/${crypto.randomUUID()}.${extension}`; const { error } = await supabase.storage.from(bucket).upload(path, file, { upsert: false, contentType: file.type }); if (error) throw error; const { data } = supabase.storage.from(bucket).getPublicUrl(path); return data.publicUrl; }
export function subscribeToRealtime(onPost, onComment, onNotification) { const channel = supabase.channel("the-circle-live").on("postgres_changes", { event: "*", schema: "public", table: "posts" }, onPost).on("postgres_changes", { event: "*", schema: "public", table: "comments" }, onComment).on("postgres_changes", { event: "INSERT", schema: "public", table: "notifications" }, onNotification).subscribe(); return () => supabase.removeChannel(channel); }

export async function findOrCreateDirectConversation(userId, otherUserId) {
  const { data: memberships, error: membershipError } = await supabase.from("conversation_members").select("conversation_id, user_id").in("user_id", [userId, otherUserId]);
  if (membershipError) throw membershipError;
  const grouped = (memberships || []).reduce((map, row) => { map[row.conversation_id] ||= new Set(); map[row.conversation_id].add(row.user_id); return map; }, {});
  const existing = Object.entries(grouped).find(([, members]) => members.size === 2);
  if (existing) return existing[0];
  const { data: conversation, error } = await supabase.from("conversations").insert({ created_by: userId, kind: "direct" }).select().single();
  if (error) throw error;
  const { error: memberError } = await supabase.from("conversation_members").insert([{ conversation_id: conversation.id, user_id: userId }, { conversation_id: conversation.id, user_id: otherUserId }]);
  if (memberError) throw memberError;
  return conversation.id;
}
export async function getMessages(conversationId) { const { data, error } = await supabase.from("messages").select("*, profiles!messages_sender_id_fkey(display_name, username, avatar_url)").eq("conversation_id", conversationId).order("created_at", { ascending: true }).limit(100); if (error) throw error; return data || []; }
export async function sendMessage(conversationId, senderId, body) { const { data, error } = await supabase.from("messages").insert({ conversation_id: conversationId, sender_id: senderId, body }).select("*, profiles!messages_sender_id_fkey(display_name, username, avatar_url)").single(); if (error) throw error; return data; }
export async function sendCallSignal(conversationId, senderId, recipientId, signalType, payload = {}) { const { error } = await supabase.from("call_signals").insert({ conversation_id: conversationId, sender_id: senderId, recipient_id: recipientId, signal_type: signalType, payload }); if (error) throw error; }
export function subscribeToConversation(conversationId, onMessage, onSignal) { const channel = supabase.channel(`conversation-${conversationId}`).on("postgres_changes", { event: "INSERT", schema: "public", table: "messages", filter: `conversation_id=eq.${conversationId}` }, onMessage).on("postgres_changes", { event: "INSERT", schema: "public", table: "call_signals", filter: `conversation_id=eq.${conversationId}` }, onSignal).subscribe(); return () => supabase.removeChannel(channel); }

export async function sendFriendRequest(senderId, recipientId) { const { data, error } = await supabase.from("friend_requests").upsert({ sender_id: senderId, recipient_id: recipientId, status: "pending" }, { onConflict: "sender_id,recipient_id" }).select().single(); if (error) throw error; return data; }
export async function respondToFriendRequest(requestId, status) { const { error } = await supabase.from("friend_requests").update({ status, updated_at: new Date().toISOString() }).eq("id", requestId); if (error) throw error; }
export async function getMarketplaceListings() { const { data, error } = await supabase.from("marketplace_listings").select("*, profiles!marketplace_listings_seller_id_fkey(display_name, username, avatar_url)").eq("status", "active").order("created_at", { ascending: false }).limit(30); if (error) throw error; return data || []; }
export async function createMarketplaceListing(sellerId, values) { const { data, error } = await supabase.from("marketplace_listings").insert({ seller_id: sellerId, ...values }).select().single(); if (error) throw error; return data; }
export async function getReels() { const { data, error } = await supabase.from("reels").select("*, profiles!reels_creator_id_fkey(display_name, username, avatar_url)").order("created_at", { ascending: false }).limit(30); if (error) throw error; return data || []; }
export async function createReel(creatorId, file, caption) { const extension = file.name.split(".").pop(); const path = `${creatorId}/${crypto.randomUUID()}.${extension}`; const { error: uploadError } = await supabase.storage.from("reels").upload(path, file, { upsert: false, contentType: file.type }); if (uploadError) throw uploadError; const { data: urlData } = supabase.storage.from("reels").getPublicUrl(path); const { data, error } = await supabase.from("reels").insert({ creator_id: creatorId, video_url: urlData.publicUrl, caption }).select().single(); if (error) throw error; return data; }
export async function getWallet(userId) { const [{ data: account, error: accountError }, { data: transactions, error: transactionError }] = await Promise.all([supabase.from("wallet_accounts").select("*").eq("user_id", userId).maybeSingle(), supabase.from("wallet_transactions").select("*").eq("user_id", userId).order("created_at", { ascending: false }).limit(20)]); if (accountError) throw accountError; if (transactionError) throw transactionError; return { account, transactions: transactions || [] }; }

export async function getActiveStatuses() { const { data, error } = await supabase.from("statuses").select("*, profiles!statuses_user_id_fkey(id, display_name, username, avatar_url)").gt("expires_at", new Date().toISOString()).order("created_at", { ascending: true }).limit(100); if (error) throw error; return data || []; }
export async function createStatus(userId, content, background, file = null) { let mediaUrl = null; let mediaType = "text"; if (file) { mediaType = file.type.startsWith("video/") ? "video" : "image"; const extension = file.name.split(".").pop(); const path = `${userId}/${crypto.randomUUID()}.${extension}`; const { error: uploadError } = await supabase.storage.from("statuses").upload(path, file, { upsert: false, contentType: file.type }); if (uploadError) throw uploadError; mediaUrl = supabase.storage.from("statuses").getPublicUrl(path).data.publicUrl; } const { data, error } = await supabase.from("statuses").insert({ user_id: userId, content, background, media_url: mediaUrl, media_type: mediaType }).select().single(); if (error) throw error; return data; }
export async function markStatusViewed(statusId, viewerId) { const { error } = await supabase.from("status_views").upsert({ status_id: statusId, viewer_id: viewerId }, { onConflict: "status_id,viewer_id" }); if (error) throw error; }
