import { useEffect, useMemo, useState } from "react";
import { supabase } from "./lib/supabase";
import { addComment, createPost, findOrCreateDirectConversation, followUser, getCurrentProfile, getFeed, getMarketplaceListings, getMessages, getNotifications, getReels, getWallet, loginUser, logoutUser, registerUser, searchProfiles, sendCallSignal, sendFriendRequest, sendMessage, subscribeToConversation, subscribeToRealtime, toggleLike, updateProfile, uploadImage } from "./api/api";
import "./App.css";

const blankAuth = { email: "", password: "", displayName: "", username: "" };
const initials = (name = "Guest") => name.split(" ").map((x) => x[0]).join("").slice(0, 2).toUpperCase() || "G";
function Avatar({ name = "Guest", size = "md" }) { return <div className={`avatar avatar-${size}`}>{initials(name)}</div>; }
function Brand() { return <div className="brand"><span className="brand-mark">◉</span> THE CIRCLE</div>; }
function ErrorBox({ message }) { return message ? <div className="form-message">{message}</div> : null; }

function AuthScreen() {
  const [mode, setMode] = useState("login"); const [form, setForm] = useState(blankAuth); const [message, setMessage] = useState(""); const [busy, setBusy] = useState(false);
  const submit = async (e) => { e.preventDefault(); setMessage(""); if (!form.email || !form.password || (mode === "register" && (!form.displayName || !form.username))) return setMessage("Jaza taarifa zote zinazohitajika."); if (mode === "register" && form.password.length < 8) return setMessage("Password iwe na angalau herufi 8."); setBusy(true); try { const result = mode === "login" ? await loginUser(form.email, form.password) : await registerUser(form); if (mode === "register" && !result.session) setMessage("Akaunti imeundwa. Angalia email yako kuthibitisha, kisha ingia."); } catch (err) { setMessage(err.message || "Imeshindikana. Jaribu tena."); } finally { setBusy(false); } };
  return <main className="auth-shell"><section className="auth-art"><Brand /><div className="art-copy"><p className="eyebrow">KARIBU KWENYE DUARA</p><h1>Watu wako.<br /><em>Hadithi zako.</em><br />Sehemu yako.</h1><p>Mtandao wa kijamii wa mazungumzo ya kweli, urafiki wa maana na jamii inayokujali.</p></div><div className="orbit orbit-one" /><div className="orbit orbit-two" /></section><section className="auth-panel"><div className="auth-card"><div className="mobile-brand"><Brand /></div><p className="eyebrow">{mode === "login" ? "KARIBU TENA" : "JIUNGE NASI"}</p><h2>{mode === "login" ? "Ingia kwenye duara" : "Fungua akaunti yako"}</h2><p className="muted">{mode === "login" ? "Endelea na watu na mambo unayopenda." : "Anza kushiriki sauti yako leo."}</p><form onSubmit={submit} className="auth-form">{mode === "register" && <><label>Jina lako<input value={form.displayName} onChange={(e) => setForm({ ...form, displayName: e.target.value })} placeholder="Amina Juma" /></label><label>Username<input value={form.username} onChange={(e) => setForm({ ...form, username: e.target.value.toLowerCase().replace(/[^a-z0-9_]/g, "") })} placeholder="amina_juma" /></label></>}<label>Email<input type="email" value={form.email} onChange={(e) => setForm({ ...form, email: e.target.value })} placeholder="wewe@example.com" /></label><label>Password<input type="password" value={form.password} onChange={(e) => setForm({ ...form, password: e.target.value })} placeholder="Angalau herufi 8" /></label><ErrorBox message={message} /><button className="button button-primary button-full" disabled={busy}>{busy ? "Inasubiri..." : mode === "login" ? "Ingia kwenye Duara" : "Jiunge na Duara"}</button></form><p className="switch-auth">{mode === "login" ? "Huna akaunti?" : "Una akaunti tayari?"} <button onClick={() => { setMode(mode === "login" ? "register" : "login"); setMessage(""); }}>{mode === "login" ? "Jisajili hapa" : "Ingia hapa"}</button></p></div></section></main>;
}

function Sidebar({ profile, active, setActive, onLogout, unread, dark, setDark }) { const links = [["home", "⌂", "Nyumbani"], ["messages", "✉", "Ujumbe"], ["friends", "♧", "Marafiki"], ["marketplace", "▣", "Marketplace"], ["reels", "▶", "Reels"], ["wallet", "◈", "Wallet"], ["discover", "✦", "Gundua"], ["notifications", "♧", `Arifa${unread ? ` (${unread})` : ""}`], ["profile", "◎", "Wasifu"]]; return <aside className="sidebar"><Brand /><nav>{links.map(([id, icon, label]) => <button className={active === id ? "nav-item active" : "nav-item"} onClick={() => setActive(id)} key={id}><span className="icon">{icon}</span>{label}</button>)}</nav><div className="sidebar-bottom"><button className="theme-toggle" onClick={() => setDark(!dark)}>{dark ? "☀ Mwanga" : "☾ Dark mode"}</button><button className="profile-mini" onClick={() => setActive("profile")}><Avatar name={profile.display_name} /><span><strong>{profile.display_name}</strong><small>@{profile.username}</small></span></button><button className="logout" onClick={onLogout}>Toka</button></div></aside>; }

function PostCard({ post, user, onRefresh }) { const [liked, setLiked] = useState((post.likes || []).some((like) => like.user_id === user.id)); const [comment, setComment] = useState(""); const [busy, setBusy] = useState(false); const like = async () => { setBusy(true); try { await toggleLike(user.id, post.id, liked); setLiked(!liked); onRefresh(); } catch {} finally { setBusy(false); } }; const sendComment = async (e) => { e.preventDefault(); if (!comment.trim()) return; setBusy(true); try { await addComment(user.id, post.id, comment.trim()); setComment(""); } catch {} finally { setBusy(false); } };
  const author = post.profiles?.display_name || "Mwanachama"; return <article className="post-card"><div className="post-head"><Avatar name={author} /><div><strong>{author}</strong><span className="post-meta">@{post.profiles?.username || "circle"} · {new Date(post.created_at).toLocaleString()}</span></div><button className="more">•••</button></div><p className="post-content">{post.content}</p>{post.media_url && <img className="post-media" src={post.media_url} alt="Post media" />}{post.comments?.[0]?.count ? <div className="post-meta comment-count">{post.comments[0].count} maoni</div> : null}<div className="post-actions"><button onClick={like} disabled={busy}>{liked ? "♥" : "♡"} <span>{(post.likes?.length || 0) + (liked && !(post.likes || []).some((x) => x.user_id === user.id) ? 1 : 0)}</span></button><button onClick={() => document.getElementById(`comment-${post.id}`)?.focus()}>◌ <span>Jibu</span></button><button>↗ <span>Shiriki</span></button></div><form className="comment-form" onSubmit={sendComment}><input id={`comment-${post.id}`} value={comment} onChange={(e) => setComment(e.target.value)} placeholder="Andika jibu..." /><button disabled={busy}>Tuma</button></form></article>; }

function Home({ profile, posts, setPosts, onPost }) { const [content, setContent] = useState(""); const [file, setFile] = useState(null); const [message, setMessage] = useState(""); const [busy, setBusy] = useState(false); const submit = async (e) => { e.preventDefault(); if (!content.trim()) return; setBusy(true); setMessage(""); try { let media = null; if (file) media = await uploadImage(profile.id, file); const post = await onPost(content.trim(), media); setPosts((current) => [{ ...post, profiles: profile, likes: [], comments: [] }, ...current]); setContent(""); setFile(null); } catch (err) { setMessage(err.message || "Post haikutumwa."); } finally { setBusy(false); } }; const refresh = async () => { try { setPosts(await getFeed()); } catch (err) { setMessage(err.message || "Feed haijasomeka."); } }; return <><header className="topbar"><div><p className="eyebrow">THE CIRCLE · LIVE</p><h1>Nyumbani</h1></div><span className="live-pill">● Live</span></header><div className="feed-layout"><main className="feed"><section className="composer"><div className="post-head"><Avatar name={profile.display_name} /><div><strong>{profile.display_name}</strong><span className="post-meta">Shiriki na duara lako</span></div></div><form onSubmit={submit}><textarea value={content} onChange={(e) => setContent(e.target.value)} placeholder="Unafikiria nini leo?" maxLength="500" /><div className="composer-foot"><label className="upload-label">＋ Picha/video<input type="file" accept="image/*,video/*" onChange={(e) => setFile(e.target.files?.[0] || null)} /></label><span className="muted">{content.length}/500</span><button className="button button-primary" disabled={busy}>{busy ? "Inatuma..." : "Shiriki"}</button></div></form><ErrorBox message={message} /></section><div className="section-heading"><h2>Kwa ajili yako</h2><button className="text-button" onClick={refresh}>Refresh</button></div>{posts.length ? posts.map((post) => <PostCard key={post.id} post={post} user={profile} onRefresh={async () => setPosts(await getFeed())} />) : <div className="empty-state"><span>◌</span><h3>Duara lako linaanza hapa</h3><p>Shiriki wazo la kwanza na ujenge mazungumzo.</p></div>}</main><aside className="right-rail"><section className="rail-card welcome"><span className="eyebrow">DUARA LAKO</span><h3>Umefika nyumbani.</h3><p>Posts, likes, maoni na arifa zinasasishwa karibu real-time.</p></section><Suggestions userId={profile.id} /></aside></div></>; }

function Suggestions({ userId }) { const [term, setTerm] = useState(""); const [results, setResults] = useState([]); const [sent, setSent] = useState({}); const search = async (e) => { const value = e.target.value; setTerm(value); if (value.length > 1) setResults(await searchProfiles(value)); else setResults([]); }; const addFriend = async (person) => { try { await sendFriendRequest(userId, person.id); setSent({ ...sent, [person.id]: true }); } catch {} }; return <section className="rail-card"><div className="rail-title"><h3>Gundua watu</h3></div><input className="search-input" value={term} onChange={search} placeholder="Tafuta mtu..." />{results.map((person) => <div className="suggestion" key={person.id}><Avatar name={person.display_name} /><span><strong>{person.display_name}</strong><small>@{person.username}</small></span><button className="follow" onClick={() => addFriend(person)}>{sent[person.id] ? "Imetumwa" : "+ Add Friend"}</button></div>)}</section>; }

function Profile({ profile, setProfile }) { const [name, setName] = useState(profile.display_name); const [bio, setBio] = useState(profile.bio || ""); const [message, setMessage] = useState(""); const save = async (e) => { e.preventDefault(); try { setProfile(await updateProfile(profile.id, { display_name: name, bio })); setMessage("Wasifu umehifadhiwa."); } catch (err) { setMessage(err.message); } }; return <div className="placeholder-page"><Avatar name={name} size="lg" /><h1>Wasifu wako</h1><form className="profile-form" onSubmit={save}><label>Jina<input value={name} onChange={(e) => setName(e.target.value)} /></label><label>Bio<textarea value={bio} onChange={(e) => setBio(e.target.value)} maxLength="160" /></label><ErrorBox message={message} /><button className="button button-primary">Hifadhi mabadiliko</button></form></div>; }
function Notifications({ items }) { return <div className="placeholder-page"><span className="placeholder-icon">♧</span><h1>Arifa zako</h1>{items.length ? items.map((n) => <p key={n.id}>{n.type === "like" ? "Mtu amependa post yako" : n.type === "comment" ? "Mtu amecomment post yako" : "Mtu amekufuata"}</p>) : <p>Bado huna arifa mpya.</p>}</div>; }

function FeatureHeader({ eyebrow, title, description }) { return <header className="feature-header"><div><p className="eyebrow">{eyebrow}</p><h1>{title}</h1><p className="muted">{description}</p></div><span className="green-badge">THE CIRCLE</span></header>; }
function Friends({ profile }) { return <div className="feature-page"><FeatureHeader eyebrow="COMMUNITY" title="Marafiki" description="Tafuta watu unaowajua na tuma ombi la urafiki." /><Suggestions userId={profile.id} /><div className="feature-callout"><strong>Urafiki wa kweli huanza na salamu.</strong><span>Ujumbe wa faragha unapatikana baada ya kuanza connection.</span></div></div>; }
function Marketplace() { const [items, setItems] = useState([]); const [loading, setLoading] = useState(true); useEffect(() => { getMarketplaceListings().then(setItems).catch(() => {}).finally(() => setLoading(false)); }, []); return <div className="feature-page"><FeatureHeader eyebrow="DUARA MARKET" title="Marketplace" description="Nunua na uza ndani ya jamii yako kwa uwazi na usalama." /><div className="feature-toolbar"><button className="button button-primary">＋ Weka bidhaa</button><span className="muted">TZS · Local first</span></div>{loading ? <p className="muted">Inapakia bidhaa...</p> : <div className="card-grid">{items.length ? items.map((item) => <article className="feature-card" key={item.id}><div className="listing-image">{item.image_url ? <img src={item.image_url} alt={item.title} /> : "▣"}</div><p className="eyebrow">{item.location || "Tanzania"}</p><h3>{item.title}</h3><strong className="price">{Number(item.price).toLocaleString()} {item.currency}</strong><p className="muted">{item.description}</p></article>) : <div className="empty-feature"><span>▣</span><h3>Marketplace inaanza hapa</h3><p>Bidhaa za kwanza zitaonekana hapa.</p></div>}</div>}</div>; }
function Reels() { const [items, setItems] = useState([]); useEffect(() => { getReels().then(setItems).catch(() => {}); }, []); return <div className="feature-page"><FeatureHeader eyebrow="SHORT STORIES" title="Reels" description="Video fupi, mawazo marefu na moments za duara lako." /><div className="reels-grid">{items.length ? items.map((reel) => <article className="reel-card" key={reel.id}><video src={reel.video_url} controls playsInline /><div><strong>{reel.profiles?.display_name || "Mwanachama"}</strong><p>{reel.caption}</p></div></article>) : <div className="empty-feature"><span>▶</span><h3>Reels zitaonekana hapa</h3><p>Shiriki video fupi na jamii yako.</p><button className="button button-primary">＋ Weka Reel</button></div>}</div></div>; }
function Wallet({ profile }) { const [wallet, setWallet] = useState(null); useEffect(() => { getWallet(profile.id).then(setWallet).catch(() => setWallet({ account: null, transactions: [] })); }, [profile.id]); const balance = wallet?.account?.balance || 0; return <div className="feature-page"><FeatureHeader eyebrow="DUARA WALLET" title="Wallet" description="Mahali salama pa kufuatilia salio na miamala yako." /><section className="wallet-balance"><span>Salio lako</span><strong>{Number(balance).toLocaleString()} {wallet?.account?.currency || "TZS"}</strong><small>Deposits, purchases na withdrawals zitaunganishwa na payment provider.</small></section><div className="feature-toolbar"><button className="button button-primary">＋ Weka pesa</button><button className="button button-soft">Toa pesa</button></div><section className="transactions"><h3>Miamala ya hivi karibuni</h3>{wallet?.transactions?.length ? wallet.transactions.map((tx) => <div className="transaction" key={tx.id}><span>{tx.type}</span><strong>{tx.amount} {tx.currency}</strong><small>{tx.status}</small></div>) : <p className="muted">Bado hakuna miamala.</p>}</section></div>; }

function Messages({ profile }) {
  const [term, setTerm] = useState(""); const [people, setPeople] = useState([]); const [person, setPerson] = useState(null); const [conversationId, setConversationId] = useState(null); const [messages, setMessages] = useState([]); const [body, setBody] = useState(""); const [call, setCall] = useState(null); const [message, setMessage] = useState("");
  const search = async (e) => { const value = e.target.value; setTerm(value); if (value.length > 1) setPeople(await searchProfiles(value)); else setPeople([]); };
  const open = async (nextPerson) => { setPerson(nextPerson); setPeople([]); setTerm(""); try { const id = await findOrCreateDirectConversation(profile.id, nextPerson.id); setConversationId(id); setMessages(await getMessages(id)); } catch (err) { setMessage(err.message); } };
  useEffect(() => { if (!conversationId) return; return subscribeToConversation(conversationId, (payload) => setMessages((current) => current.some((m) => m.id === payload.new.id) ? current : [...current, payload.new]), (payload) => handleSignal(payload.new)); }, [conversationId]);
  const send = async (e) => { e.preventDefault(); if (!body.trim() || !conversationId) return; try { const sent = await sendMessage(conversationId, profile.id, body.trim()); setMessages((current) => current.some((m) => m.id === sent.id) ? current : [...current, sent]); setBody(""); } catch (err) { setMessage(err.message); } };
  const handleSignal = async (signal) => { if (!person || signal.recipient_id !== profile.id) return; if (signal.signal_type === "ringing") setCall({ incoming: true, active: false }); if (signal.signal_type === "hangup") { call?.peer?.close(); setCall(null); } if (signal.signal_type === "offer") { const peer = createPeer(false); await peer.setRemoteDescription(signal.payload); const answer = await peer.createAnswer(); await peer.setLocalDescription(answer); await sendCallSignal(conversationId, profile.id, person.id, "answer", answer); setCall({ peer, active: true, incoming: false }); } if (signal.signal_type === "answer" && call?.peer) await call.peer.setRemoteDescription(signal.payload); if (signal.signal_type === "ice" && call?.peer && signal.payload) await call.peer.addIceCandidate(signal.payload); };
  const createPeer = (initiator) => { const peer = new RTCPeerConnection({ iceServers: [{ urls: "stun:stun.l.google.com:19302" }] }); peer.onicecandidate = (e) => { if (e.candidate) sendCallSignal(conversationId, profile.id, person.id, "ice", e.candidate); }; peer.ontrack = (e) => { const video = document.getElementById("remote-video"); if (video) video.srcObject = e.streams[0]; }; if (initiator) navigator.mediaDevices.getUserMedia({ audio: true, video: true }).then(async (stream) => { stream.getTracks().forEach((track) => peer.addTrack(track, stream)); const offer = await peer.createOffer(); await peer.setLocalDescription(offer); await sendCallSignal(conversationId, profile.id, person.id, "offer", offer); }); return peer; };
  const startCall = async () => { if (!conversationId || !person) return; await sendCallSignal(conversationId, profile.id, person.id, "ringing"); setCall({ peer: createPeer(true), active: true, incoming: false }); };
  const acceptCall = () => { setCall((current) => ({ ...current, incoming: false, active: true })); };
  const hangup = async () => { if (call?.peer) call.peer.close(); if (conversationId && person) await sendCallSignal(conversationId, profile.id, person.id, "hangup"); setCall(null); };
  return <div className="messages-page"><div className="messages-header"><div><p className="eyebrow">FARAGHA</p><h1>Ujumbe</h1></div><span className="live-pill">● Realtime</span></div><div className="messages-layout"><aside className="contacts"><input className="search-input" value={term} onChange={search} placeholder="Tafuta mtu wa kuzungumza naye..." />{people.map((p) => <button className="contact" key={p.id} onClick={() => open(p)}><Avatar name={p.display_name} /><span><strong>{p.display_name}</strong><small>@{p.username}</small></span></button>)}{!people.length && <p className="muted contact-hint">Tafuta username au jina kuanza ujumbe.</p>}</aside><section className="conversation"><div className="conversation-top">{person ? <><Avatar name={person.display_name} /><div><strong>{person.display_name}</strong><small>@{person.username}</small></div><button className="call-button" onClick={startCall}>☎ Piga simu</button></> : <p className="muted">Chagua mtu kuanza mazungumzo ya faragha.</p>}</div><div className="messages-list">{messages.map((m) => <div className={m.sender_id === profile.id ? "bubble mine" : "bubble"} key={m.id}>{m.body}<small>{new Date(m.created_at).toLocaleTimeString()}</small></div>)}</div>{person && <form className="message-form" onSubmit={send}><input value={body} onChange={(e) => setBody(e.target.value)} placeholder="Andika ujumbe wa faragha..." /><button className="button button-primary">Tuma</button></form>}{message && <ErrorBox message={message} />}</section></div>{call && <div className="call-overlay"><div className="call-card"><p className="eyebrow">{call.incoming ? "SIMU INAYOINGIA" : "SIMU YA THE CIRCLE"}</p><h2>{call.incoming ? `${person?.display_name} anakupigia` : `Unazungumza na ${person?.display_name}`}</h2><video id="remote-video" autoPlay playsInline /><div className="call-actions">{call.incoming && <button className="button button-primary" onClick={acceptCall}>Pokea</button>}<button className="button button-danger" onClick={hangup}>Funga simu</button></div></div></div>}</div>;
}

export default function App() {
  const [session, setSession] = useState(null); const [profile, setProfile] = useState(null); const [active, setActive] = useState("home"); const [posts, setPosts] = useState([]); const [notifications, setNotifications] = useState([]); const [booting, setBooting] = useState(true); const [dark, setDark] = useState(() => localStorage.getItem("the-circle-theme") === "dark");
  useEffect(() => { document.documentElement.dataset.theme = dark ? "dark" : "light"; localStorage.setItem("the-circle-theme", dark ? "dark" : "light"); }, [dark]);
  const load = async (user) => { const [p, f, n] = await Promise.all([getCurrentProfile(user.id), getFeed(), getNotifications(user.id)]); setProfile(p); setPosts(f); setNotifications(n); };
  useEffect(() => { supabase.auth.getSession().then(async ({ data }) => { setSession(data.session); if (data.session) await load(data.session.user); setBooting(false); }); const { data: listener } = supabase.auth.onAuthStateChange(async (_event, next) => { setSession(next); if (next) await load(next.user); else { setProfile(null); setPosts([]); } }); return () => listener.subscription.unsubscribe(); }, []);
  useEffect(() => { if (!session) return; return subscribeToRealtime(async (payload) => { if (payload.eventType === "INSERT") setPosts(await getFeed()); }, async () => setPosts(await getFeed()), async () => setNotifications(await getNotifications(session.user.id))); }, [session]);
  const onPost = async (content, media) => createPost(session.user.id, content, media); const logout = async () => logoutUser();
  if (booting) return <div className="loading-screen"><Brand /><p>Inafungua duara...</p></div>; if (!session || !profile) return <AuthScreen />;
  return <div className="app-shell"><Sidebar profile={profile} active={active} setActive={setActive} onLogout={logout} unread={notifications.filter((n) => !n.read_at).length} dark={dark} setDark={setDark} /><div className="main-area">{active === "home" && <Home profile={profile} posts={posts} setPosts={setPosts} onPost={onPost} />}{active === "messages" && <Messages profile={profile} />}{active === "friends" && <Friends profile={profile} />}{active === "marketplace" && <Marketplace />}{active === "reels" && <Reels />}{active === "wallet" && <Wallet profile={profile} />}{active === "profile" && <Profile profile={profile} setProfile={setProfile} />}{active === "notifications" && <Notifications items={notifications} />}{active === "discover" && <div className="placeholder-page"><span className="placeholder-icon">✦</span><h1>Gundua</h1><p>Tafuta watu wa kujiunga nao kwenye duara lako.</p><Suggestions userId={profile.id} /></div>}</div></div>;
}
