import { useEffect, useMemo, useState } from "react";
import { supabase } from "./lib/supabase";
import { addComment, createPost, followUser, getCurrentProfile, getFeed, getNotifications, loginUser, logoutUser, registerUser, searchProfiles, subscribeToRealtime, toggleLike, updateProfile, uploadImage } from "./api/api";
import "./App.css";

const blankAuth = { email: "", password: "", displayName: "", username: "" };
const initials = (name = "Guest") => name.split(" ").map((x) => x[0]).join("").slice(0, 2).toUpperCase() || "G";
function Avatar({ name = "Guest", size = "md" }) { return <div className={`avatar avatar-${size}`}>{initials(name)}</div>; }
function Brand() { return <div className="brand"><span className="brand-mark">◉</span> THE CIRCLE</div>; }
function ErrorBox({ message }) { return message ? <div className="form-message">{message}</div> : null; }

function AuthScreen() {
  const [mode, setMode] = useState("login"); const [form, setForm] = useState(blankAuth); const [message, setMessage] = useState(""); const [busy, setBusy] = useState(false);
  const submit = async (e) => { e.preventDefault(); setMessage(""); if (!form.email || !form.password || (mode === "register" && (!form.displayName || !form.username))) return setMessage("Jaza taarifa zote zinazohitajika."); if (mode === "register" && form.password.length < 8) return setMessage("Password iwe na angalau herufi 8."); setBusy(true); try { const result = mode === "login" ? await loginUser(form.email, form.password) : await registerUser(form); if (mode === "register" && !result.session) setMessage("Akaunti imeundwa. Angalia email yako kuthibitisha, kisha ingia."); } catch (err) { setMessage(err.message || "Imeshindikana. Jaribu tena."); } finally { setBusy(false); } };
  return <main className="auth-shell"><section className="auth-art"><Brand /><div className="art-copy"><p className="eyebrow">KARIBU KWENYE DUARA</p><h1>Watu wako.<br /><em>Hadithi zako.</em><br />Sehemu yako.</h1><p>Mtandao wa kijamii wa mazungumzo ya kweli, urafiki wa maana na jamii inayokujali.</p></div><div className="orbit orbit-one" /><div className="orbit orbit-two" /></section><section className="auth-panel"><div className="auth-card"><div className="mobile-brand"><Brand /></div><p className="eyebrow">{mode === "login" ? "KARIBU TENA" : "JIUNGE NASI"}</p><h2>{mode === "login" ? "Ingia kwenye duara" : "Fungua akaunti yako"}</h2><p className="muted">{mode === "login" ? "Endelea na watu na mambo unayopenda." : "Anza kushiriki sauti yako leo."}</p><form onSubmit={submit} className="auth-form">{mode === "register" && <><label>Jina lako<input value={form.displayName} onChange={(e) => setForm({ ...form, displayName: e.target.value })} placeholder="Amina Juma" /></label><label>Username<input value={form.username} onChange={(e) => setForm({ ...form, username: e.target.value.toLowerCase().replace(/[^a-z0-9_]/g, "") })} placeholder="amina_juma" /></label></>}<label>Email<input type="email" value={form.email} onChange={(e) => setForm({ ...form, email: e.target.value })} placeholder="wewe@example.com" /></label><label>Password<input type="password" value={form.password} onChange={(e) => setForm({ ...form, password: e.target.value })} placeholder="Angalau herufi 8" /></label><ErrorBox message={message} /><button className="button button-primary button-full" disabled={busy}>{busy ? "Inasubiri..." : mode === "login" ? "Ingia kwenye Duara" : "Jiunge na Duara"}</button></form><p className="switch-auth">{mode === "login" ? "Huna akaunti?" : "Una akaunti tayari?"} <button onClick={() => { setMode(mode === "login" ? "register" : "login"); setMessage(""); }}>{mode === "login" ? "Jisajili hapa" : "Ingia hapa"}</button></p></div></section></main>;
}

function Sidebar({ profile, active, setActive, onLogout, unread }) { const links = [["home", "⌂", "Nyumbani"], ["discover", "✦", "Gundua"], ["notifications", "♧", `Arifa${unread ? ` (${unread})` : ""}`], ["profile", "◎", "Wasifu"]]; return <aside className="sidebar"><Brand /><nav>{links.map(([id, icon, label]) => <button className={active === id ? "nav-item active" : "nav-item"} onClick={() => setActive(id)} key={id}><span className="icon">{icon}</span>{label}</button>)}</nav><div className="sidebar-bottom"><button className="profile-mini" onClick={() => setActive("profile")}><Avatar name={profile.display_name} /><span><strong>{profile.display_name}</strong><small>@{profile.username}</small></span></button><button className="logout" onClick={onLogout}>Toka</button></div></aside>; }

function PostCard({ post, user, onRefresh }) { const [liked, setLiked] = useState((post.likes || []).some((like) => like.user_id === user.id)); const [comment, setComment] = useState(""); const [busy, setBusy] = useState(false); const like = async () => { setBusy(true); try { await toggleLike(user.id, post.id, liked); setLiked(!liked); onRefresh(); } catch {} finally { setBusy(false); } }; const sendComment = async (e) => { e.preventDefault(); if (!comment.trim()) return; setBusy(true); try { await addComment(user.id, post.id, comment.trim()); setComment(""); } catch {} finally { setBusy(false); } };
  const author = post.profiles?.display_name || "Mwanachama"; return <article className="post-card"><div className="post-head"><Avatar name={author} /><div><strong>{author}</strong><span className="post-meta">@{post.profiles?.username || "circle"} · {new Date(post.created_at).toLocaleString()}</span></div><button className="more">•••</button></div><p className="post-content">{post.content}</p>{post.media_url && <img className="post-media" src={post.media_url} alt="Post media" />}{post.comments?.[0]?.count ? <div className="post-meta comment-count">{post.comments[0].count} maoni</div> : null}<div className="post-actions"><button onClick={like} disabled={busy}>{liked ? "♥" : "♡"} <span>{(post.likes?.length || 0) + (liked && !(post.likes || []).some((x) => x.user_id === user.id) ? 1 : 0)}</span></button><button onClick={() => document.getElementById(`comment-${post.id}`)?.focus()}>◌ <span>Jibu</span></button><button>↗ <span>Shiriki</span></button></div><form className="comment-form" onSubmit={sendComment}><input id={`comment-${post.id}`} value={comment} onChange={(e) => setComment(e.target.value)} placeholder="Andika jibu..." /><button disabled={busy}>Tuma</button></form></article>; }

function Home({ profile, posts, setPosts, onPost }) { const [content, setContent] = useState(""); const [file, setFile] = useState(null); const [message, setMessage] = useState(""); const [busy, setBusy] = useState(false); const submit = async (e) => { e.preventDefault(); if (!content.trim()) return; setBusy(true); setMessage(""); try { let media = null; if (file) media = await uploadImage(profile.id, file); const post = await onPost(content.trim(), media); setPosts((current) => [{ ...post, profiles: profile, likes: [], comments: [] }, ...current]); setContent(""); setFile(null); } catch (err) { setMessage(err.message || "Post haikutumwa."); } finally { setBusy(false); } }; const refresh = async () => { try { setPosts(await getFeed()); } catch (err) { setMessage(err.message || "Feed haijasomeka."); } }; return <><header className="topbar"><div><p className="eyebrow">THE CIRCLE · LIVE</p><h1>Nyumbani</h1></div><span className="live-pill">● Live</span></header><div className="feed-layout"><main className="feed"><section className="composer"><div className="post-head"><Avatar name={profile.display_name} /><div><strong>{profile.display_name}</strong><span className="post-meta">Shiriki na duara lako</span></div></div><form onSubmit={submit}><textarea value={content} onChange={(e) => setContent(e.target.value)} placeholder="Unafikiria nini leo?" maxLength="500" /><div className="composer-foot"><label className="upload-label">＋ Picha/video<input type="file" accept="image/*,video/*" onChange={(e) => setFile(e.target.files?.[0] || null)} /></label><span className="muted">{content.length}/500</span><button className="button button-primary" disabled={busy}>{busy ? "Inatuma..." : "Shiriki"}</button></div></form><ErrorBox message={message} /></section><div className="section-heading"><h2>Kwa ajili yako</h2><button className="text-button" onClick={refresh}>Refresh</button></div>{posts.length ? posts.map((post) => <PostCard key={post.id} post={post} user={profile} onRefresh={async () => setPosts(await getFeed())} />) : <div className="empty-state"><span>◌</span><h3>Duara lako linaanza hapa</h3><p>Shiriki wazo la kwanza na ujenge mazungumzo.</p></div>}</main><aside className="right-rail"><section className="rail-card welcome"><span className="eyebrow">DUARA LAKO</span><h3>Umefika nyumbani.</h3><p>Posts, likes, maoni na arifa zinasasishwa karibu real-time.</p></section><Suggestions userId={profile.id} /></aside></div></>; }

function Suggestions({ userId }) { const [term, setTerm] = useState(""); const [results, setResults] = useState([]); const search = async (e) => { const value = e.target.value; setTerm(value); if (value.length > 1) setResults(await searchProfiles(value)); else setResults([]); }; return <section className="rail-card"><div className="rail-title"><h3>Gundua watu</h3></div><input className="search-input" value={term} onChange={search} placeholder="Tafuta mtu..." />{results.map((person) => <div className="suggestion" key={person.id}><Avatar name={person.display_name} /><span><strong>{person.display_name}</strong><small>@{person.username}</small></span><button className="follow" onClick={() => followUser(userId, person.id, false)}>+ Fuata</button></div>)}</section>; }

function Profile({ profile, setProfile }) { const [name, setName] = useState(profile.display_name); const [bio, setBio] = useState(profile.bio || ""); const [message, setMessage] = useState(""); const save = async (e) => { e.preventDefault(); try { setProfile(await updateProfile(profile.id, { display_name: name, bio })); setMessage("Wasifu umehifadhiwa."); } catch (err) { setMessage(err.message); } }; return <div className="placeholder-page"><Avatar name={name} size="lg" /><h1>Wasifu wako</h1><form className="profile-form" onSubmit={save}><label>Jina<input value={name} onChange={(e) => setName(e.target.value)} /></label><label>Bio<textarea value={bio} onChange={(e) => setBio(e.target.value)} maxLength="160" /></label><ErrorBox message={message} /><button className="button button-primary">Hifadhi mabadiliko</button></form></div>; }
function Notifications({ items }) { return <div className="placeholder-page"><span className="placeholder-icon">♧</span><h1>Arifa zako</h1>{items.length ? items.map((n) => <p key={n.id}>{n.type === "like" ? "Mtu amependa post yako" : n.type === "comment" ? "Mtu amecomment post yako" : "Mtu amekufuata"}</p>) : <p>Bado huna arifa mpya.</p>}</div>; }

export default function App() {
  const [session, setSession] = useState(null); const [profile, setProfile] = useState(null); const [active, setActive] = useState("home"); const [posts, setPosts] = useState([]); const [notifications, setNotifications] = useState([]); const [booting, setBooting] = useState(true);
  const load = async (user) => { const [p, f, n] = await Promise.all([getCurrentProfile(user.id), getFeed(), getNotifications(user.id)]); setProfile(p); setPosts(f); setNotifications(n); };
  useEffect(() => { supabase.auth.getSession().then(async ({ data }) => { setSession(data.session); if (data.session) await load(data.session.user); setBooting(false); }); const { data: listener } = supabase.auth.onAuthStateChange(async (_event, next) => { setSession(next); if (next) await load(next.user); else { setProfile(null); setPosts([]); } }); return () => listener.subscription.unsubscribe(); }, []);
  useEffect(() => { if (!session) return; return subscribeToRealtime(async (payload) => { if (payload.eventType === "INSERT") setPosts(await getFeed()); }, async () => setPosts(await getFeed()), async () => setNotifications(await getNotifications(session.user.id))); }, [session]);
  const onPost = async (content, media) => createPost(session.user.id, content, media); const logout = async () => logoutUser();
  if (booting) return <div className="loading-screen"><Brand /><p>Inafungua duara...</p></div>; if (!session || !profile) return <AuthScreen />;
  return <div className="app-shell"><Sidebar profile={profile} active={active} setActive={setActive} onLogout={logout} unread={notifications.filter((n) => !n.read_at).length} /><div className="main-area">{active === "home" && <Home profile={profile} posts={posts} setPosts={setPosts} onPost={onPost} />}{active === "profile" && <Profile profile={profile} setProfile={setProfile} />}{active === "notifications" && <Notifications items={notifications} />}{active === "discover" && <div className="placeholder-page"><span className="placeholder-icon">✦</span><h1>Gundua</h1><p>Tafuta watu wa kujiunga nao kwenye duara lako.</p><Suggestions userId={profile.id} /></div>}</div></div>;
}
